### ISSUE TITLE
How to setup external login providers such as google

### ISSUE THREAD

**Issue by jeminpro** [MoonriseSoftwareCalifornia/AspNetCore.Identity.CosmosDb#12]
Please can you suggest how to setup external login providers such as google, facebook etc. with this setup using default packages such as [Microsoft.AspNetCore.Authentication.Google](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.Google). As per the Microsoft documentation the configuration  needs to be as below

```
services.AddAuthentication().AddGoogle(googleOptions =>
    {
        googleOptions.ClientId = configuration["Authentication:Google:ClientId"];
        googleOptions.ClientSecret = configuration["Authentication:Google:ClientSecret"];
    });
```

But the AddAuthentication in package `AspNetCore.Identity.CosmosDb` the extension method  AddAuthentication is inside the package.

**Comment by toiyabe** [comment]
Hello @jeminpro, I just added to the README an example of how to add Google and Microsoft external providers. Thank you for your question!
