### ISSUE TITLE
Upgrade to .net 8

### ISSUE THREAD

**Issue by vincentnl** [MoonriseSoftwareCalifornia/AspNetCore.Identity.CosmosDb#16]
Having an error that says it cannot find an implementation of Clone() in EntityFramework.Cosmos 7.0.2

**Comment by adambarath** [comment]
Hi, 
Any update on this?

**Comment by toiyabe** [comment]
Hello @adambarath, this is happening today!

**Comment by toiyabe** [comment]
@adambarath, just pushed a couple updates.  #16 upgrade to .Net 8, and #13 support for generic keys.
